logging {
  debug: off
  to_syslog: yes
}

nodelist {
  node {
    name: pve-dl360p
    nodeid: 1
    quorum_votes: 1
    ring0_addr: 192.168.1.15
  }
  node {
    name: pve2
    nodeid: 2
    quorum_votes: 1
    ring0_addr: 192.168.1.5
  }
}

quorum {
  provider: corosync_votequorum
}

totem {
  cluster_name: barcluster
  config_version: 2
  interface {
    linknumber: 0
  }
  ip_version: ipv4-6
  link_mode: passive
  secauth: on
  version: 2
}

