config {
}

devices {
	issue_discards = 1
}

allocation {
}

log {
}

backup {
}

shell {
}

global {
}

activation {
}

report {
}

dmeventd {
}

devices {
     global_filter=["r|/dev/zd.*|","r|/dev/rbd.*|"]
}
