defaults {
    user_friendly_names yes
    find_multipaths yes
}
devices {
    device {
        vendor "FreeNAS"
        product "iSCSI.*"
        path_grouping_policy multibus
        path_checker tur
        prio alua
        failback immediate
    }
}
