# CI workflow for testing/building Nix flake
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - nixosConfigurations.installer-base.config.system.build.toplevel
          - nixosConfigurations.gaming.config.system.build.toplevel
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Run checks
        run: |
          nix flake check || true
          nix develop .#lint --command bash -c "luacheck . && stylua --check . && statix check && alejandra --check . && yamllint ." || true

      - name: Build ${{ matrix.package }}
        run: nix build .#${{ matrix.package }}
