# CI workflow for testing/building Nix flake
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: self-hosted
    strategy:
      matrix:
        package:
          - nixosConfigurations.gaming.config.system.build.toplevel
    steps:
      - name: Checkout flake
        uses: actions/checkout@v4

      - name: Build ${{ matrix.package }}
        run: nix build .#${{ matrix.package }}
