[global]
keyboard = "en-us"
country = "us"
fqdn = "pve-test.lamhub.com"
mailto = "lam@lamhub.com"
timezone = "@TIMEZONE@"
root_password = "@ROOT_PASSWORD@"
root-ssh-keys = [ "@SSH_PUBKEY@" ]

[disk-setup]
filesystem = "zfs"
disk-list = [ "vda" ]
zfs.ashift = 12
zfs.raid = "raid0"

[network]
source = "from-dhcp"

[first-boot]
source = "from-url"
ordering = "network-online"
url = "@FIRST_BOOT_URL@"
