# This file contains a list of modules which are not supported by Proxmox VE 

# nvidiafb see bugreport https://bugzilla.proxmox.com/show_bug.cgi?id=701
blacklist nvidiafb

# LamT: passthrough Fibre and LSI to FreeNAS
blacklist qla2xxx
blacklist mpt3sas
